title: Mateus Hiro Nagata # your name (or website title) here
logo: "HEC_Paris.svg.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.Res. in Economics and Decision Sciences - HEC Paris
  <br><br>
  M.A. in Economic Theory - ITAM
  <br>
  B.A. in Economic Sciences  - University of Brasilia
  <br><br>
  <a href="https://www.linkedin.com/in/mateus-hiro-nagata-048388172/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.com/citations?user=krNpwU0AAAAJ&hl=en&oi=ao">View my Google Scholar</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
